rdbms:
  type: postgres
  host: localhost
  port: 5432
  database: minilabdb
  username: minilab
  # password dibaca dari environment variable: POSTGRES_PASSWORD
  sources:
    - name: customers_from_db
      query: "SELECT * FROM customers"
      target: "raw/rdbms/customers/customers_from_db.csv"
    - name: orders_from_db
      query: "SELECT * FROM orders"
      target: "raw/rdbms/orders/orders_from_db.csv"

files:
  - name: customers_from_csv
    source_type: csv
    path: "data/input/csv/customers.csv"
    target: "raw/csv/customers/customers_from_csv.csv"
  - name: products_from_xlsx
    source_type: xlsx
    path: "data/input/xlsx/products.xlsx"
    target: "raw/xlsx/products/products_from_xlsx.csv"
